### ISSUE TITLE
Any one else facing this issue while pulling in the changes ?

### ISSUE THREAD

**Issue by sayskar500** [py3-coder/Hacktober_Repo_22#200]
![image](https://user-images.githubusercontent.com/55600400/193903978-dab0c2e6-bf75-4bab-ad5f-00ddf0876e89.png)

**Comment by aishwaryanevrekar** [comment]
Yes

**Comment by sayskar500** [comment]
@py3-coder kindly have a look at this

**Comment by py3-coder** [comment]
@aishwaryanevrekar & @sayskar500  Don't worry  I got to know the same issue in afternoon.
As far I can understand the issue till now :
Temporary Soln: The main is issue which your are facing that your local didn't got sync with original repo.
For that Just try to sync from web or incase you can clone it again to local.
and Doing R&D on it get the root cause.
Don't worry will able to resolve it soon.

**Comment by py3-coder** [comment]
Now you can go for it use same command it will work.
Actually I found a file in cpp folder which is creating the issue i remove it.
Just Go forward 
@aishwaryanevrekar & @sayskar500  
Now i think issue is resolve from my end.

**Comment by sayskar500** [comment]
Yeah, the issue is now resolved @py3-coder ... thanks !! .. closing this issue
